module.exports.descriptors = [
    'forest',
    'ancient',
    'retrified',
    'roaring',
    'cascade',
    'tumbling',
    'silent',
    'redwood',
    'bullfrog',
    'maple',
    'misty',
    'elk',
    'grizzly',
    'ocean',
    'sea',
    'sky',
    'dusty',
    'diamond'
]

module.exports.places = [
    'flats',
    'village',
    'canyon',
    'pond',
    'group camp',
    'horse camp',
    'ghost town',
    'camp',
    'dispersed camp',
    'backcountry',
    'river',
    'creek',
    'creekside',
    'bay',
    'spring',
    'bayshore',
    'sands',
    'mule camp',
    'hunting camp',
    'cliffs',
    'hollow'

]